/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mbmrwckffzicnboaysnh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibXJ3Y2tmZnppY25ib2F5c25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyMjc2NzQsImV4cCI6MjEwNjgwMzY3NH0.TifV6OQ-02_24lUC2P4RDTvVv_C8-okCboQw5COMrf0"